version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ethank
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crypto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    depends_on:
      - db
    environment:
      RPC_NETWORK_URL: https://mainnet.helius-rpc.com/?api-key=
      RPC_NETWORK_KEY: # Your API key here
      DATABASE_URL: postgres://ethank:password@db:5432/crypto
    ports:
      - "8080:8080"
    command: ["crypto-backend"]

volumes:
  postgres_data: